### ISSUE TITLE
counter in gui lags (but not in the tui version)

### ISSUE THREAD

**Issue by dlesnoff** [ansiwave/nimwave_starter#1]
I have run the gui version on my OS Ubuntu 22.04.3.
The counter widget takes several seconds to update (even with the -d:release flag) in the gui. It is much slower than in the terminal (tui) version.
Is it expected?

I have not run any profiler to investigate further.

**Comment by oakes** [comment]
This was caused by the mouse queue filling up faster than it was being emptied. I just pushed a fix; please try it out and let me know if there are still any problems.

**Comment by dlesnoff** [comment]
I have git pull latest commit and rebuilt the gui version with the new common.
Every ten seconds, it still lags and forget some inputs.

EDIT: I edited the title, since I did not experienced these lags in the tui version.

**Comment by oakes** [comment]
Can't seem to repro the 10 second issue in my ubuntu VM. Does it only happen when you move/click the mouse really quickly?

**Comment by dlesnoff** [comment]
I rm'ed the build and retried. It seems to work well (unless we click really quickly, it seems to me that it can add 1 to the counter in this case)! Thank you!
